# Generated by Django 3.1 on 2021-06-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('modified_by', models.DateTimeField(blank=True, null=True)),
                ('max_hours_limit', models.IntegerField(default=1, null=True)),
                ('screenshot_interval', models.IntegerField(default=0, null=True)),
                ('emp_photo_interval', models.IntegerField(default=0, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.employee')),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaveTypes',
            fields=[
                ('leave_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'leaves_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveCredit',
            fields=[
                ('leave_credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('credited', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('financial_year', models.IntegerField(blank=True, default=2021, null=True)),
                ('month_credited', models.IntegerField(blank=True, default=1, null=True)),
                ('credited_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.employee')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.leavetypes')),
            ],
            options={
                'db_table': 'emp_leaves_credits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_balance', models.FloatField(blank=True, default=0, null=True)),
                ('current_balance', models.FloatField(blank=True, default=0, null=True)),
                ('financial_year', models.IntegerField(blank=True, default=2020, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('leave_type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.employee')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.leavetypes')),
            ],
            options={
                'db_table': 'emp_leaves_balance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveApplication',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('requested_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('leave_type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('num_leaves', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.leavetypes')),
            ],
            options={
                'db_table': 'leaves_applications',
                'managed': True,
            },
        ),
    ]
