# Generated by Django 3.0.4 on 2021-04-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaveapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaveapplication',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
