# Generated by Django 3.1 on 2021-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
