# Generated by Django 3.0.4 on 2021-05-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_auto_20210430_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleaveapplication',
            name='no_of_days',
        ),
        migrations.AddField(
            model_name='employeeleaveapplication',
            name='leave_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.LeaveTypes'),
            preserve_default=False,
        ),
    ]
