# Generated by Django 3.1 on 2021-06-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_auto_20210627_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=models.DateField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
