# Generated by Django 3.0.4 on 2021-05-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_auto_20210501_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleavebalance',
            old_name='open_balance',
            new_name='available_balance',
        ),
    ]
