# Generated by Django 3.0.4 on 2021-05-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_auto_20210503_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleavebalance',
            old_name='available_balance',
            new_name='previous_balance',
        ),
    ]
