# Generated by Django 3.0.4 on 2021-05-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_auto_20210503_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveCredit',
            fields=[
                ('leave_credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('credited', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('financial_year', models.IntegerField(blank=True, default=2021, null=True)),
                ('month_credited', models.IntegerField(blank=True, default=1, null=True)),
                ('credited_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.Employee')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave_management.LeaveTypes')),
            ],
            options={
                'db_table': 'emp_leaves_credits',
                'managed': True,
            },
        ),
    ]
