# Generated by Django 3.1 on 2021-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0007_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaveapplication',
            name='leave_type_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
