# Generated by Django 3.1 on 2021-06-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0008_employeeleaveapplication_leave_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaveapplication',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
