# Generated by Django 3.1 on 2021-06-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0009_employeeleaveapplication_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalance',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='leave_type_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
