# Generated by Django 3.1 on 2021-06-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0010_auto_20210604_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaveapplication',
            name='num_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
